#!/bin/bash
# Copyright (c) 2014, Redmaner

up=$PWD

if [ $# -gt 0 ]; then
	case "$1" in
		--all) 
		rm -f $up/.configuration
		rm -rf $up/MIUIv5
		rm -rf $up/MIUI6
		rm -rf $up/MergedXML
		rm -rf $up/resources;;

		--resources)
		rm -rf $up/resources;;

		--config)
		rm -f $up/.configuration;;

		--compare_repos)
		rm -rf $up/MIUIv5
		rm -rf $up/MIUI6;;

		--merged)
		rm -rf $up/MergedXML;;
	esac
else
	rm -f $up/.configuration
	rm -rf $up/MergedXML
fi

