#!/bin/bash

up=$PWD

# Define bash colors for Mac OSX / Linux
case `uname -s` in
    Darwin) 
           txtrst='\033[0m' # Color off
           txtred='\033[0;31m' # Red
           txtgrn='\033[0;32m' # Green
           txtblu='\033[0;34m' # Blue
           ;;
    *)
           txtrst='\e[0m' # Color off
           txtred='\e[0;31m' # Red
           txtgrn='\e[0;32m' # Green
           txtblu='\e[0;36m' # Blue
           ;;
esac

source $up/.configuration
mkdir -p $up/resources_lean 

echo -e "${txtblu}\nLean merge enabled: generate lean resources${txtrst}"
if [ -d $orig_dir/MiuiGallery.apk ]; then
	$up/custom_ignore_generator $orig_dir/MiuiGallery.apk/res/values/strings.xml $up/resources_lean/custom_merge1.xml cityname_ MiuiGallery.apk
	$up/res_tools --add_custom $untranslateable_list $up/resources_lean/custom_merge1.xml
fi
if [ -d $orig_dir/Transfer.apk ]; then
	$up/custom_ignore_generator $orig_dir/Transfer.apk/res/values/strings.xml $up/resources_lean/custom_merge2.xml country_name_ Transfer.apk
	$up/res_tools --add_custom $untranslateable_list $up/resources_lean/custom_merge2.xml
	$up/custom_ignore_generator $orig_dir/Transfer.apk/res/values/strings.xml $up/resources_lean/custom_merge3.xml deprecated_ Transfer.apk
	$up/res_tools --add_custom $untranslateable_list $up/resources_lean/custom_merge3.xml
fi
