#!/bin/bash
# Copyright (c) 2014, Redmaner

VERSION=4.0.0
up=$PWD

# Define bash colors for Mac OSX / Linux
case `uname -s` in
    Darwin) 
           txtrst='\033[0m' # Color off
           txtred='\033[0;31m' # Red
           txtgrn='\033[0;32m' # Green
           txtblu='\033[0;34m' # Blue
           ;;
    *)
           txtrst='\e[0m' # Color off
           txtred='\e[0;31m' # Red
           txtgrn='\e[0;32m' # Green
           txtblu='\e[0;36m' # Blue
           ;;
esac

# Source information
source $up/configure
source $up/.configuration

if [ ! -f $up/bools ]; then
	echo -e "${txtred}ERROR: bools file not detected\nCopy bools.default to bools and edit it to your needs\nThen run merge again${txtrst}"; exit
else
	source $up/bools
fi

if [ $lean_merge == "enabled" ]; then
	source $up/lean_merge
fi

if [ $dir_mode == custom ]; then
	values=values-$lang_iso
else
	values=values
fi

echo -e "
#################################################
 MA-XML-MERGE V$VERSION
#################################################
"

for apk in $(find $orig_dir -iname "*.apk" | sort -rh); do
	apk_name=$(basename $apk)
	if [ -d $targ_dir/$apk_name ]; then
		if [ -f "$orig_dir/$apk_name/res/values/strings.xml" ] && [ -f "$targ_dir/$apk_name/res/values-$lang_iso/strings.xml" ]; then
			($up/merge_strings $orig_dir/$apk_name/res/$values/strings.xml $targ_dir/$apk_name/res/values-$lang_iso/strings.xml $new_dir/$apk_name/res/values-$lang_iso/strings.xml $apk_name $untranslateable_list)&
		elif [ -f "$orig_dir/$apk_name/res/values/strings.xml" ] && [ ! -f "$targ_dir/$apk_name/res/values-$lang_iso/strings.xml" ] && [ $merge_non_exsisting == "enabled" ]; then
			($up/merge_strings $orig_dir/$apk_name/res/$values/strings.xml $up/dummy.xml $new_dir/$apk_name/res/values-$lang_iso/strings.xml $apk_name $untranslateable_list)&
		fi
	fi
done
wait

for apk in $(find $orig_dir -iname "*.apk" | sort -rh); do
	apk_name=$(basename $apk)
	if [ -d $targ_dir/$apk_name ]; then
		if [ -f "$orig_dir/$apk_name/res/values/arrays.xml" ] && [ -f "$targ_dir/$apk_name/res/values-$lang_iso/arrays.xml" ]; then
			($up/merge_arrays $orig_dir/$apk_name/res/$values/arrays.xml $targ_dir/$apk_name/res/values-$lang_iso/arrays.xml $new_dir/$apk_name/res/values-$lang_iso/arrays.xml $apk_name $untranslateable_list)&
		elif [ -f "$orig_dir/$apk_name/res/values/arrays.xml" ] && [ ! -f "$targ_dir/$apk_name/res/values-$lang_iso/arrays.xml" ] && [ $merge_non_exsisting == "enabled" ]; then
			($up/merge_arrays $orig_dir/$apk_name/res/$values/arrays.xml $up/dummy.xml $new_dir/$apk_name/res/values-$lang_iso/arrays.xml $apk_name $untranslateable_list)&
		fi
	fi
done
wait

for apk in $(find $orig_dir -iname "*.apk" | sort -rh); do
	apk_name=$(basename $apk)
	if [ -d $targ_dir/$apk_name ]; then
		if [ -f "$orig_dir/$apk_name/res/values/plurals.xml" ] && [ -f "$targ_dir/$apk_name/res/values-$lang_iso/plurals.xml" ]; then
			($up/merge_plurals $orig_dir/$apk_name/res/$values/plurals.xml $targ_dir/$apk_name/res/values-$lang_iso/plurals.xml $new_dir/$apk_name/res/values-$lang_iso/plurals.xml $apk_name $untranslateable_list)&
		elif [ -f "$orig_dir/$apk_name/res/values/plurals.xml" ] && [ ! -f "$targ_dir/$apk_name/res/values-$lang_iso/plurals.xml" ] && [ $merge_non_exsisting == "enabled" ]; then
			($up/merge_plurals $orig_dir/$apk_name/res/$values/plurals.xml $up/dummy.xml $new_dir/$apk_name/res/values-$lang_iso/plurals.xml $apk_name $untranslateable_list)&
		fi
	fi
done
wait


# MergeCustom: Function to merge non matching apk's.
# For example AOSP applications: SystemUI.apk is equal to MiuiSystemUI.apk
MergeCustom () {
custom_apk=$1
apk_name=$2
if [ -f "$orig_dir/$apk_name/res/values/strings.xml" ] && [ -f "$targ_dir/$custom_apk/res/values-$lang_iso/strings.xml" ]; then
	($up/merge_strings $orig_dir/$apk_name/res/$values/strings.xml $targ_dir/$custom_apk/res/values-$lang_iso/strings.xml $new_dir/$apk_name/res/values-$lang_iso/strings.xml)&
fi
}

if [ "$aosp" == "yes" ]; then
	MergeCustom "CalendarGoogle.apk" "Calendar.apk"
	MergeCustom "DeskClockGoogle.apk" "DeskClock.apk"
	MergeCustom "EmailGoogle.apk" "Email.apk"
	MergeCustom "Exchange2Google.apk" "Exchange2.apk"
	MergeCustom "GalleryGoogle.apk" "MiuiGallery.apk"
	MergeCustom "Music2.apk" "Music.apk"
	MergeCustom "SystemUI.apk" "MiuiSystemUI.apk"
fi	
