#!/bin/bash

parse_ignorelist_mxcr () {
TARGET_FILE=$1
NEW_FILE=$2
cat $TARGET_FILE | grep '<item ' | while read ignore_string; do
	ITEM_APP=$(echo $ignore_string | awk '{print $3}' | cut -d'"' -f2)
	ITEM_FILE=$(echo $ignore_string | awk '{print $4}' | cut -d'"' -f2)
	ITEM_NAME=$(echo $ignore_string | awk '{print $5}' | cut -d'"' -f2)
	if [ $ITEM_FILE == "strings.xml" ]; then
		echo ''$ITEM_APP' '$ITEM_NAME''
	fi
done > $NEW_FILE
}

if [ $# -gt 0 ]; then
	case "$1" in
		--parse_ignorelist)
		parse_ignorelist_mxcr "$2" "$3";;
	esac
fi
